# Generated by Django 2.2.7 on 2019-11-18 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 18, 21, 14, 20, 801176))),
                ('reps', models.CharField(blank=True, max_length=1000, null=True)),
                ('sets', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout')),
            ],
        ),
    ]
