# Generated by Django 2.2.7 on 2019-11-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sets', models.CharField(blank=True, max_length=10, null=True)),
                ('repetitions', models.CharField(blank=True, max_length=10, null=True)),
                ('rest_time', models.CharField(blank=True, max_length=10, null=True)),
                ('img1Path', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2Path', models.ImageField(blank=True, null=True, upload_to='')),
                ('instruction', models.CharField(blank=True, max_length=10, null=True)),
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Category')),
            ],
        ),
    ]
