# Generated by Django 2.2.7 on 2019-11-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sets', models.CharField(blank=True, max_length=10, null=True)),
                ('repetitions', models.CharField(blank=True, max_length=10, null=True)),
                ('rest_time', models.CharField(blank=True, max_length=10, null=True)),
                ('img1Path', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2Path', models.ImageField(blank=True, null=True, upload_to='')),
                ('instruction', models.CharField(blank=True, max_length=10, null=True)),
                ('muscle_group', models.CharField(blank=True, max_length=10, null=True)),
                ('challenge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=20000, null=True)),
                ('workout_split', models.CharField(blank=True, max_length=1000000, null=True)),
                ('calorie_intake', models.CharField(blank=True, max_length=100000, null=True)),
                ('nutrition', models.CharField(blank=True, max_length=100000, null=True)),
                ('challenge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('challenge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
            ],
        ),
    ]
